[package]
name = "bubbles"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
relm4 = { version = "0.10.0", features = ["css", "macros", "libadwaita", "gnome_48"] }
tokio = { version = "1.47", features = ["fs", "net", "io-util", "time"] }
gtk = { version = "0.10", package = "gtk4" }