name: AppBuild

on:
  push:
    branches: [ "main" ]
    paths:
    - "bubbles-app/**"

jobs:
  build-flatpak:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install Flatpak tooling
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder podman
          flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          flatpak install --user -y org.gnome.Platform//49 org.gnome.Sdk//49 \
            org.freedesktop.Sdk.Extension.rust-stable//25.08

      - name: Build prebuilt artifacts
        run: cd bubbles-app && ./prebuild.bash

      - name: Build Flatpak
        run: |
          flatpak-builder --user --install --force-clean build-dir \
            bubbles-app/de.gonicus.Bubbles.json

      - name: Bundle Flatpak
        run: |
          flatpak build-bundle ~/.local/share/flatpak/repo \
            de.gonicus.Bubbles.flatpak de.gonicus.Bubbles

      - name: Upload bundle
        uses: actions/upload-artifact@v5
        with:
          name: de.gonicus.Bubbles.flatpak
          path: de.gonicus.Bubbles.flatpak
